image: python:3.8

variables:
  GIT_DEPTH: 0


check_code_style:
  tags: ['docker']
  script:
    - "pip install tox"
    - "tox -e check_codestyle"

check_types:
  tags: ['docker']
  script:
    - "pip install tox"
    - "tox -e check_types"

unit_tests:
  tags: ['docker']
  script:
    - "pip install tox"
    - "tox -e py"

check_newsfile:
  tags: ['docker']
  script:
    - "echo sr"
    - "git show-ref"
    - "echo gr"
    - "git remote -v"
    - "echo gb"
    - "git branch"
    - "echo gt"
    - "git tag"
    - "python -m pip install towncrier"
    - "scripts-dev/check_newsfragment.sh $CI_MERGE_REQUEST_IID"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
